[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
watchPatterns = [
  "src/**",
  "public/**",
  "package.json",
  "package-lock.json",
  "vite.config.js",
  "vite.config.ts",
  "index.html",
  "tailwind.config.js",
  "tailwind.config.ts",
  "postcss.config.js",
  "jsconfig.json",
  "tsconfig.json",
  "railway.toml"
]
